# Generated by Django 4.0.4 on 2022-07-11 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='bookedby',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('booked', 'booked'), ('notbooked', 'notbooked')], default='notbooked', max_length=20),
        ),
    ]
