# Generated by Django 4.0.4 on 2022-07-16 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_reservation_bookedby_reservation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='whenavail',
            field=models.CharField(default='it is available', max_length=25),
        ),
    ]
